"""
Markdown Documentation Generator

يقوم بتوليد توثيق فني بتنسيق Markdown نقي بدون أي HTML أو CSS.
التركيز على المحتوى المنطقي والتنسيق النصي البسيط فقط.
"""

import logging
from core_ai.ai_engine.doc.doc_generator import DocumentationGenerator
import datetime
logger = logging.getLogger(__name__)


class MarkdownGenerator(DocumentationGenerator):
    def _format_output(self, content, data):
        """
        تنسيق المحتوى كـ Markdown نقي مع الحفاظ على الهيكل الناتج من الـ Agents
        """
        content_str = str(content) if content else ""

        # تحديد نوع الشرح
        explanation_type = data.get('explanation_type') if data else None
        if explanation_type == 'high_level':
            exp_type_display = "Executive Overview"
        else:
            exp_type_display = "Technical Documentation"
            
        created_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        
        # محاولة استخراج اسم الملف من البيانات
        filename = "DOCUMENTATION"
        if data:
            if data.get('filename'):
                filename = data.get('filename').upper()
            elif data.get('original_filename'):
                filename = data.get('original_filename').upper()
        
        if filename == "DOCUMENTATION":
            import re
            file_match = re.search(r'File:\s*([^\s\n]+)', content_str)
            if file_match:
                filename = file_match.group(1).upper()

        # بناء الـ header
        header = (
            f"# 📜 {filename}\n"
            f"> **STATUS:** ✅ VERIFIED | **DATE:** {created_at}\n"
            f"> **TYPE:** {exp_type_display}\n"
            f"> **GENERATED BY:** AutoTest & DocGen\n\n"
            f"---\n"
        )

        # إضافة الـ diagram إذا كان موجود
        diagram = ""
        image_url = data.get('image_url', '') if data else ''
        if image_url:
            diagram = f"\n## 📊 Architecture Visualization\n![Class Diagram]({image_url})\n\n---\n"

        # تنظيف المحتوى من رأس الملف
        import re
        clean_content = re.sub(r'^File:.*?\n', '', content_str, flags=re.MULTILINE).strip()

        # الـ footer
        footer = (
            f"\n\n---\n"
            f"*Generated by **AutoTest & DocGen** | Technical Intelligence Unit*\n"
            f"*Last Updated: {created_at}*"
        )

        final_content = f"{header}{diagram}\n{clean_content}{footer}"
        return final_content