# Generated by Django 4.2.14 on 2026-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0008_mongogeneratedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoProjectAIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project AI Explanation (MongoDB)',
                'verbose_name_plural': 'Project AI Explanations (MongoDB)',
                'db_table': 'fake_project_ai_explanations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MongoProjectAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_ids', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Analysis Result (MongoDB)',
                'verbose_name_plural': 'Project Analysis Results (MongoDB)',
                'db_table': 'fake_project_analysis_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MongoProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Document (MongoDB)',
                'verbose_name_plural': 'Project Documents (MongoDB)',
                'db_table': 'fake_project_documents',
                'managed': False,
            },
        ),
    ]
