# Generated by Django 4.2.14 on 2026-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0008_mongogeneratedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoProjectAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_ids', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Analysis Result (MongoDB)',
                'verbose_name_plural': 'Project Analysis Results (MongoDB)',
                'db_table': 'fake_project_analysis_results',
                'managed': False,
            },
        ),
    ]
