# Generated by Django 4.2.14 on 2026-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0009_mongoprojectanalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoProjectAIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project AI Explanation (MongoDB)',
                'verbose_name_plural': 'Project AI Explanations (MongoDB)',
                'db_table': 'fake_project_ai_explanations',
                'managed': False,
            },
        ),
    ]
