# Generated by Django 4.2.14 on 2026-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0010_mongoprojectaiexplanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Document (MongoDB)',
                'verbose_name_plural': 'Project Documents (MongoDB)',
                'db_table': 'fake_project_documents',
                'managed': False,
            },
        ),
    ]
