from rest_framework import serializers
from core_upm.models import CodeArtifact 

class CodeArtifactSerializer(serializers.ModelSerializer):
    """
    Serializer for CodeArtifact listing/upload. 
    Uses storage_reference instead of code_content.
    """
    
    project_name = serializers.CharField(source='project.project_name', read_only=True)


    class Meta:
        model = CodeArtifact
        fields = [
            'code_id','project_name','file_name',
            'upload_date', 'code_language', 'code_version', 'storage_reference'
        ]
        # storage_reference is read-only here as it's generated by the service layer, not provided by the user
        # code_content is handled separately in the view and not part of the model
        read_only_fields = ['code_id','project_name','upload_date','storage_reference']



class CodeArtifactDetailSerializer(serializers.ModelSerializer):
    """
    Serializer to show full artifact details, including the storage reference.
    """
    project_name = serializers.CharField(source='project.project_name', read_only=True)

    class Meta:
        model = CodeArtifact
        fields = [
            'code_id', 'project_name', 'file_name', 'upload_date', 
            'code_language', 'code_version', 'storage_reference'
        ]
        read_only_fields = fields        