# Generated by Django 5.2.8 on 2025-11-19 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Role Description')),
                ('permissions_list', models.JSONField(default=dict, verbose_name='Permissions List')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Project ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_description', models.TextField(blank=True, verbose_name='Project Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Creation User')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CodeArtifact',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='code ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('code_language', models.CharField(max_length=50, verbose_name='Code Language')),
                ('code_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code Version')),
                ('storage_reference', models.CharField(max_length=512, verbose_name='Storage Reference')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_artifacts', to='core_upm.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Code Artifact',
                'verbose_name_plural': 'Code Artifacts',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('signup_date', models.DateTimeField(auto_now_add=True, verbose_name='Signup Date')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_upm.role', verbose_name='Default Role')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
