# Generated by Django 5.2.8 on 2025-12-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeartifact',
            name='storage_reference',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Storage Reference'),
        ),
    ]
