# Generated by Django 5.2.8 on 2026-03-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0002_alter_codeartifact_storage_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('ADMIN', 'Admin'), ('REVIEWER', 'Reviewer')], default='DEVELOPER', max_length=20, unique=True, verbose_name='Role Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen'),
        ),
    ]
