# Generated by Django 5.2.8 on 2026-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0002_alter_codeartifact_storage_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeartifact',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='Version Number'),
        ),
    ]
