# Generated by Django 5.2.8 on 2026-03-17 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0004_codeartifact_folder_version_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeartifact',
            name='code_version',
        ),
        migrations.RemoveField(
            model_name='codeartifact',
            name='version_number',
        ),
        migrations.AlterField(
            model_name='codeartifact',
            name='code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Code ID'),
        ),
        migrations.AlterField(
            model_name='codeartifact',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='codeartifact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core_upm.project'),
        ),
        migrations.AlterField(
            model_name='codeartifact',
            name='storage_reference',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Storage Reference (GridFS ID)'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Folder ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core_upm.repository', verbose_name='Repository'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Repo ID'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Version ID'),
        ),
    ]
