# Generated by Django 5.2.8 on 2026-03-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0005_remove_codeartifact_code_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='core_upm.repository', verbose_name='Repository'),
        ),
    ]
