# Generated by Django 5.2.8 on 2026-03-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0003_role_role_type_userprofile_is_online_and_more'),
        ('core_upm', '0007_repository_github_fields'),
    ]

    operations = [
    ]
