# Generated by Django 5.2.8 on 2026-04-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_upm', '0009_add_project_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_user_date_idx',
        ),
    ]
