# Generated by Django 5.2.8 on 2025-12-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم')),
                ('notification_type', models.CharField(choices=[('PROJECT_CREATED', 'تم إنشاء مشروع جديد'), ('PROJECT_DELETED', 'تم حذف مشروع'), ('CODE_ADDED', 'تم إضافة كود جديد'), ('CODE_DELETED', 'تم حذف كود'), ('DOCUMENTATION_EXPORTED', 'تم تصدير ملف توثيق'), ('SYSTEM_ALERT', 'تنبيه نظام')], max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='رسالة الإشعار')),
                ('priority', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='MEDIUM', max_length=20, verbose_name='الأولوية')),
                ('related_id', models.CharField(blank=True, help_text='معرف المشروع أو الكود أو الملف المرتبط', max_length=100, null=True, verbose_name='معرف العنصر المرتبط')),
                ('related_type', models.CharField(blank=True, help_text='نوع العنصر (project, code, documentation)', max_length=50, verbose_name='نوع العنصر المرتبط')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('SENT', 'تم الإرسال'), ('FAILED', 'فشل في الإرسال'), ('READ', 'تم قراءته')], default='PENDING', max_length=20, verbose_name='حالة الإشعار')),
                ('send_attempts', models.IntegerField(default=0, verbose_name='عدد محاولات الإرسال')),
                ('max_send_attempts', models.IntegerField(default=3, verbose_name='الحد الأقصى للمحاولات')),
                ('email_sent', models.BooleanField(default=False, verbose_name='تم إرسال الإيميل')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الإيميل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('metadata', models.JSONField(blank=True, help_text='بيانات إضافية JSON للإشعار', null=True, verbose_name='البيانات الإضافية')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_email', 'status'], name='notificatio_user_em_b0d1f7_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
